# Welcome to Jekyll!
#

# Site settings
title: OSCP JOURNEY
description: |
  Welcome to the Blog.
owner: Yogendra Swaroop Srivastava # or company name

email: yogendra.swaroop.srivastava@gmail.com
baseurl: "/oscp" # the subpath of your site, e.g. /blog
url: "http://yogendra-swaroop.tech" # the base hostname & protocol for your site
social:
  linkedin-square: https://linkedin.com/in/yogendra-swaroop-srivastava-8aa45874/
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
