# Welcome to Jekyll!
#

# Site settings
title: OSCP JOURNEY
description: |
  Welcome to the Blog.
owner: Yogendra Swaroop Srivastava # or company name

email: yogendra.swaroop.srivastava@gmail.com
baseurl: "/oscp" # the subpath of your site, e.g. /blog
url: "http://yogendra-swaroop.tech" # the base hostname & protocol for your site
social:
  linkedin-square: https://linkedin.com/in/yogendra-swaroop-srivastava-8aa45874/
 
# Build settings
markdown: kramdown

theme: jekyll-theme-time-machine
